### ISSUE TITLE
添加java资料

### ISSUE THREAD

**Issue by DrS1X** [AndrewAndJenny/AlgorithmTrain#1]
《java编程思想》网页版：java进阶教材
https://lingcoder.github.io/OnJava8/#/sidebar

**Comment by Shawnul** [comment]
I have added it to the repositories, if you have more excellent Java books, you can continue to upload


> 《java编程思想》网页版：java进阶教材
> https://lingcoder.github.io/OnJava8/#/sidebar

**Comment by Shawnul** [comment]
close
